apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace:  {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: "windows"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: {{ .Values.appName }}-wincontainer
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
